.firebaserc
.gitignore
firebase.json

Ajout des fichiers de config firebase pour pouvoir hoster le site

Ajout des infos de deploy

---

src/app/app.module.ts
src/app/components/constitution-page/results/results-grade/grade-average/grade-average.component.html
src/app/components/constitution-page/results/results-grade/grade-relationship/grade-relationship.component.html
src/app/components/constitution-page/results/results-grade/grade-relationship/grade-relationship.component.spec.ts
src/app/components/constitution-page/results/results-grade/grade-relationship/grade-relationship.component.ts
src/app/components/constitution-page/results/results-grade/results-grade.component.html
src/app/components/constitution-page/results/results-grade/results-grade.component.ts
src/app/components/template/heatmap/heatmap.component.html
src/app/components/template/heatmap/heatmap.component.spec.ts
src/app/components/template/heatmap/heatmap.component.ts
src/app/components/template/radar/radar.component.ts
src/app/types/charts.ts

* Ajout de la sous-page "Relations" dans la page des résultats d'une Grade Constitution.
* Ajout d'une carte des chaleurs entre les utilisateurs.
* Ajout d'une explication pour la lecture de la table des moyennes entre les utilisateurs.
* Le radar chart a maintenant une couleur plus distinctive du fond pour mieux lire les données. Il est maintenant sous forme d'aire plutôt que seulement par périmètre.
* Ajout d'un template pour les heatmaps.

Début sous-page des résultats "Relations"

---

package-lock.json
package.json
src/app/app.module.ts
src/app/components/admin-page/admin-page.component.html
src/app/components/admin-page/admin-page.component.ts
src/app/components/admin-page/manage-invites/manage-invites.component.ts
src/app/components/admin-page/manage-roles/manage-roles.component.html
src/app/components/admin-page/manage-roles/manage-roles.component.scss
src/app/components/admin-page/manage-roles/manage-roles.component.spec.ts
src/app/components/admin-page/manage-roles/manage-roles.component.ts
src/app/components/profile-page/profile-page.component.ts
src/app/components/users-page/users-page.component.html
src/app/components/users-page/users-page.component.ts
src/app/types/role.ts

* Passage à Chelys 2.5.0
* Nouvel onglet pour gérer les rôles d'un participant.
* Formatage amélioré des heures d'une invitation.
* L'affichage de la liste des rôles ne dépend plus de l'ordre dans lequel ils sont stockés sur la base de donnée.
* Utilisation de la requête `UrsReqEditProfile` au lieu de `UsrReqEdit`.
Équivalent Yagta : https://github.com/TableauBits/Kalimba/pull/29

Gestion des rôles depuis la page d'administration

---

src/app/components/admin-page/new-constitution/new-constitution.component.ts
src/app/components/constitution-page/manage-songs/manage-songs.component.html
src/app/components/constitution-page/random-song/random-song.component.html
src/app/components/constitution-page/results/results-favorites/results-favorites.component.html
src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.html
src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.html
src/app/components/constitution-page/results/results-grade/grade-ranking/grade-ranking.component.html
src/app/components/constitution-page/song-list/song-list.component.html
src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.html
src/app/components/constitution-page/votes/votes-grade/vote-navigator/vote-navigator.component.html
src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
src/app/components/delete-song-warning/delete-song-warning.component.html
src/styles.scss

- La limite arbitraire de nombre de charactères à été augmenté à 100 pour le titre de la chanson et le nom de artiste.
- Dans le cas ou il y aurait un débordement, le titre complet de la chanson sera tronqué en utilisant `text-overflow`
- Les noms des artistes s'affichent avant le titre des chansons
[Kalimba!30](https://github.com/TableauBits/Kalimba/pull/30)

Amélioration de l'enregistrement et l'affichage des chansons

---

src/app/components/constitution-page/export/export.component.ts

* Ajout des options d'export `JSON` et `JSON (dev)`.
* Création du type `ExportJSON`.
* close #60

Ajout de l'export en format JSON

---

src/app/app.module.ts
src/app/services/auth.service.ts

* Envoie d'une requête HTTP toutes les 10 minutes pour maintenir Kalimba ouvert.
* Dépend de https://github.com/TableauBits/Kalimba/pull/35

Maintient de la connexion à Kalimba

---

src/app/components/constitution-page/export/export.component.ts
src/app/components/constitution-page/results/results-grade/grade-profile/grade-profile.component.html
src/app/components/constitution-page/results/results-grade/grade-profile/grade-profile.component.ts
src/app/components/constitution-page/results/results-grade/results-grade.component.html
src/app/services/download.service.spec.ts
src/app/services/download.service.ts

Ajout d'un export JSON des résultats d'une constitution à partir de l'onglet "Mon Profil" de la page de résultat. Ce téléchargement est disponible pour les membres ayant le rôle Admin.
* Ajout d'un export des résultats d'une constitution.
* Création du service `download`.

Export des résultats d'une constitution

---

src/app/components/invite-page/invite-page.component.ts
src/app/services/auth.service.ts
src/environments/environment.prod.ts
src/environments/environment.ts

Création de la release v1.2.0 "Liquid Funk". Voir description de #69.

Liquid Funk

---

src/app/components/constitution-page/constitution.component.ts
src/app/components/constitution-page/manage-songs/manage-songs.component.ts

* Mise à jours automatique des champs disponibles dans le pop-up "Gérer mes chansons" lorsqu'on supprime ou ajoute une chanson.
* Close #71

Mise à jours en temps réel du pop-up "Gérer mes chansons"

---

src/app/components/admin-page/new-constitution/new-constitution.component.scss
src/app/components/constitution-page/constitution.component.html
src/app/components/constitution-page/manage-songs/manage-songs.component.html
src/app/components/constitution-page/results/results-favorites/results-favorites.component.scss
src/app/components/constitution-page/results/results-grade/grade-average/grade-average.component.html
src/app/components/constitution-page/results/results-grade/grade-average/grade-average.component.scss
src/app/components/constitution-page/results/results-grade/grade-average/grade-average.component.ts
src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.html
src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.scss
src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.html
src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.scss
src/app/components/constitution-page/results/results-grade/grade-profile/grade-profile.component.html
src/app/components/constitution-page/results/results-grade/grade-ranking/grade-ranking.component.html
src/app/components/constitution-page/song-list/song-list.component.html
src/app/components/constitution-page/song-list/song-list.component.scss
src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
src/app/components/constitution-page/votes/votes-grade/votes-grade.component.scss
src/styles.scss

* Ajout de tooltips pour expliquer certains boutons (Liste de Chansons, Zone Électorale, Soirée Électorale).
* Utilisation des images de profils au lieu des pseudos pour les tableaux de Notes et de Moyennes pour plus de lisibilité.
* Ajout d'une contour autour des images de profils pour ajouter du constraste.
* Correction des couleurs des `mat-form`, `mat-select` et `mat-option`.
* Correction du titre de certaines colonnes / popup.
* Réduction du nombre de chiffre significatif pour le radar chart.

Correction pour 8ème Xénocratie

---

src/app/components/constitution-page/export/export.component.scss
src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.html
src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.scss
src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.ts
src/app/components/constitution-page/votes/votes-grade/vote-navigator/vote-navigator.component.html
src/app/components/constitution-page/votes/votes-grade/vote-navigator/vote-navigator.component.scss

Cette Hotfix pour #76 rétabli les couleurs aux boutons de navigateurs ainsi que le comportement de ces boutons de favoris.

Future Funk: Hotfix 1

---

src/app/components/constitution-page/results/results-favorites/results-favorites.component.html
src/app/components/constitution-page/results/results-favorites/results-favorites.component.scss
src/app/components/constitution-page/results/results-favorites/results-favorites.component.ts

* Ajout d'une nouvelle statistique sur les favoris en comptant le nombre de favoris que chaque utilisateur a reçu.

Calcul du nombre de favoris reçu par chaque utilisateur dans l'onglet des résultats

---

src/app/components/constitution-page/results/results-favorites/results-favorites.component.html
src/app/components/constitution-page/results/results-grade/grade-average/grade-average.component.html
src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.html
src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.html
src/app/components/constitution-page/results/results-grade/grade-profile/grade-profile.component.html
src/app/components/constitution-page/results/results-grade/grade-ranks/grade-ranks.component.html
src/app/components/constitution-page/results/results-grade/grade-relationship/grade-relationship.component.html
src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
src/app/components/template/chord/chord.component.html
src/app/components/template/chord/chord.component.ts
src/app/components/template/heatmap/heatmap.component.html
src/app/components/template/heatmap/heatmap.component.ts
src/app/components/template/histogram/histogram.component.html
src/app/components/template/histogram/histogram.component.ts
src/app/components/template/pie/pie.component.html
src/app/components/template/pie/pie.component.ts
src/app/components/template/radar/radar.component.html
src/app/components/template/radar/radar.component.ts
src/app/components/template/scatter/scatter.component.html
src/app/components/template/scatter/scatter.component.ts
src/app/types/charts.ts

* Utilisation d'un id pour distinguer les graphes afin d'éviter des erreurs dans Echarts lorsqu'on essaye d'accéder à un élément HTML.
* Ajout de la class `Charts`.
* Close #119

Correction de l'utilisation des graphes avec le passage d'un id

---

src/app/components/template/chord/chord.component.html
src/app/components/template/heatmap/heatmap.component.html
src/app/components/template/histogram/histogram.component.html
src/app/components/template/pie/pie.component.html
src/app/components/template/radar/radar.component.html
src/app/components/template/scatter/scatter.component.html
src/app/types/charts.ts

* La taille des graphes s'adapte maintenant aux dimensions du navigateur y compris lorsqu'on modifie la taille de la fenêtre.
* Close #121

Redimensionnement automatique des graphes

---

src/app/components/current-constitution-page/current-constitution-page.component.html
src/app/components/current-constitution-page/current-constitution-page.component.scss
src/app/components/current-constitution-page/current-constitution-page.component.ts

* Séparation des constitutions en fonction de si elles sont en cours ou terminées en 2 différentes tables.

Séparation des constitutions en fonction de si elles sont en cours ou terminées

---

package-lock.json
package.json

* Mise à jour des versions de `package.json` et `package-lock.json`

Mise à jour des versions de `package.json` et `package-lock.json`

---

src/app/components/users-page/users-page.component.html
src/app/components/users-page/users-page.component.scss

* Retrait des utilisateurs tests (cobayes) de la page des utilisateurs.
* Formatage des fichiers `.scss` et `.html` de la page des utilisateurs.

Révision de la page des utilisateurs

---

src/app/components/constitution-page/song-list/song-list.component.html
src/app/components/constitution-page/song-list/song-list.component.scss
src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
src/app/components/constitution-page/votes/votes-grade/votes-grade.component.scss

* Révision du visuel des boutons affichant les votes sur les cards et des boutons menant au navigateur sur les tables.
* Le bouton affichant les votes ne dépasse plus de la card.

Correction de l'affichage des votes sur les cards

---

src/app/components/constitution-page/results/results-grade/grade-ranks/grade-ranks.component.html
src/app/components/constitution-page/results/results-grade/grade-ranks/grade-ranks.component.ts
src/app/components/template/scatter/scatter.component.ts
src/app/types/charts.ts

* Le tooltip donne désormais le nom et l'auteur de la chanson.
* Les valeurs de l'axe X étaient décalées de 1.
* Regroupement des différents paramètres d'un scatter graph dans `ScatterConfig` pour faciliter la personnalisation.

Utilisation d'une configuration pour les Scatter Graph

---

src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.html
src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.ts
src/app/components/constitution-page/results/results-grade/grade-ranks/grade-ranks.component.ts
src/app/types/charts.ts

* Ajout de la répartition des notes en fonction des langues dans la zone des résultats avec un scatter graph.
* Uniformisation de l'interface dans la section des favoris.

Ajout de la répartition des notes en fonction des langues

---

src/app/components/constitution-page/results/results-constitution/results-constitution.component.html
src/app/components/constitution-page/results/results-constitution/results-constitution.component.ts
src/app/types/math.ts

* Affichage de l'année moyenne et médiane des chansons.
* Ajout de la fonction `median`.
* Regroupement des attributs en lieu avec le graphique sur l'année de sortie des chansons.

Affichage de l'année moyenne et médiane des chansons

---

src/app/components/constitution-page/results/results-constitution/results-constitution.component.ts
src/app/components/constitution-page/results/results-favorites/results-favorites.component.html
src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.html
src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.ts
src/app/components/constitution-page/results/results-grade/grade-profile/grade-profile.component.html
src/app/components/constitution-page/results/results-grade/grade-relationship/grade-relationship.component.ts
src/app/components/constitution-page/results/results-grade/results-grade.component.html
src/app/types/utils.ts

* Ajout de la répartition des notes d'un utilisateur en fonction de : `favoris`, `décennie de sortie` et `genre`.
* Séparation du titre et de l'auteur dans les tables.
* Ajout de la fonction `toDecade`.

Répartition des notes d'un utilisateur en fonction de : `favoris`, `décennie de sortie` et `genre`

---

src/app/components/constitution-page/manage-songs/manage-songs.component.html
src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.html
src/app/components/navbar/navbar.component.html

* Ajout d'un bouton avec les paramètres optionnels dans la soirée électorale.
* Révision du texte de boutons pour mieux refléter leur action.

Corrections pour 10ème Xénocratie

---

package-lock.json
package.json

* Mise à jour des versions de package.json et package-lock.json

Mise à jour des versions de package.json et package-lock.json

---

package-lock.json
package.json

Création de la release v.1.5.2 "Vaporwave". Cette release inclut :
* https://github.com/TableauBits/Yatga/pull/139
* https://github.com/TableauBits/Yatga/pull/140
* https://github.com/TableauBits/Yatga/pull/141

Vaporwave (Slowed + Reverb)

---

src/app/services/auth.service.ts
src/app/types/environment.ts
src/environments/environment.prod.ts
src/environments/environment.ts

Récemment, Fly.io à décidé d'enlever l'accès à des IPV4 dédiées gratuites, et il a fallu par conséquent mettre à jour notre configuration de déploiement. Cette PR s'occupe de la mise à jour de la connectivité avec Kalimba.
* Mise à jour de l'environment de production

Mise à jour de la méthode de connexion à kalimba suite aux changements sur Fly.io

---

package-lock.json
src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.html
src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.ts
src/app/components/template/inv-histogram/inv-histogram.component.ts
src/app/types/charts.ts

* Ajout d'un argument pour changer la couleur de la heatmap d'un `InvHistogram`. Changement de la palette de couleur pour celui de la soirée électorale.
* Correction de vulnérabilités avec `npm audit fix`.

Ajout d'un argument pour mettre à jour la couleur d'une heatmap d'un InvHistogram

---

package-lock.json
src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.html
src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.ts
src/app/components/invite-page/invite-page.component.ts
src/app/components/template/inv-histogram/inv-histogram.component.ts
src/app/types/charts.ts

* Retrait de la partie `WebsocketPort` de l'environnement quand en production.

Correction de l'URL pour utiliser une invitation

---

src/app/components/constitution-page/results/results-constitution/results-constitution.component.ts
src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.html
src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.ts
src/app/types/results.ts

* Ajout d'un filtre sur les utilisateurs lors du visionnement des notes données par un participant à un autre (ou toute la constitution).
* La variable `CONSTITUTION_USER_ID` est exportable.

Ajout d'un filtre sur les utilisateurs pour les notes d'un participant

---

.github/workflows/firebase-hosting-merge.yml

* Le déploiement se fait désormais sur une `release` au lieu du merge d'une branche.

Changement du déploiement sur Firebase

---

src/app/components/rewind-page/rewind-fav/rewind-fav.component.scss
src/app/components/rewind-page/rewind-page.component.html
src/app/components/rewind-page/rewind-page.component.scss
src/app/components/rewind-page/rewind-team/rewind-team.component.scss
src/app/components/rewind-page/rewind-user-score/rewind-user-score.component.scss

* Correction de la taille de l'onglet équipe du Rewind.
* Retrait des warnings dû à des divisions dans certains fichiers `scss`.

Correction de la taille de l'onglet équipe du Rewind

---

src/app/components/constitution-page/results/results-constitution/results-constitution.component.html
src/app/components/constitution-page/results/results-constitution/results-constitution.component.ts
src/styles.scss

* Répartition des pays des chansons d'une constitution dans les résultats d'une constitution.

Répartition des pays des chansons d'une constitution

---

src/app/components/constitution-page/song-list/song-list.component.html
src/app/components/constitution-page/song-list/song-list.component.ts
src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
src/app/components/constitution-page/votes/votes-grade/votes-grade.component.ts

* Ajout d'une option pour classer les chansons d'une constitution dans un ordre aléatoire.

Ajout d'une option pour mélanger les chansons d'une constitution
