- src/app/components/navbar/navbar.component.html
* L'icône signalant la déconnexion de Kalimba avait été perdu dans le refactoring de la navbar.
> Retour de l'icône signalant la déconnexion

- src/app/app.module.ts
- src/app/components/constitution-page/results/results-favorites/results-favorites.component.html
- src/app/components/constitution-page/results/results-favorites/results-favorites.component.scss
- src/app/components/constitution-page/results/results-grade/grade-relationship/grade-relationship.component.html
- src/app/components/constitution-page/results/results-grade/grade-relationship/grade-relationship.component.scss
- src/app/components/constitution-page/results/results-grade/grade-relationship/grade-relationship.component.ts
- src/app/components/template/chord/chord.component.html
- src/app/components/template/chord/chord.component.spec.ts
- src/app/components/template/chord/chord.component.ts
- src/app/types/charts.ts
La visualisation par graphe n'est pas terminée mais aurait d'abord besoin de plus de feedback de la part de la communauté en condition réel afin de bien comprendre les besoins.
* Ajout d'une visualisation des relations dans un graphe.
* La visualisation par graphe possède plusieurs paramètres (re-générer les coordonnées, appliquer la force, retirer certains lien entre les noeuds) pour mieux les utiliser.
* Dans la sous-page de la résultat dans l'onglet "Favoris", changement du fond de couleur en gris du compteur de favoris pour éviter de croire à un bouton. 
* Ajout d'un template pour générer les graphes.
> Ajout d'une visualisation des relations en Graphe

- src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.html
- src/app/components/template/heatmap/heatmap.component.ts
* La longueur des colonnes de la table des notes des utilisateurs dans une soirée électorale est désormais fixe et ne varie plus en fonction des utilisateurs présents.
* Retrait du titre "Punch Card" du hover d'une case de la heatmap
> Corrections mineures dans l'interface de la soirée électorale et de la heatmap

- src/app/components/admin-page/new-constitution/new-constitution.component.ts
- src/app/components/constitution-page/manage-songs/manage-songs.component.html
- src/app/components/constitution-page/manage-songs/manage-songs.component.ts
- src/app/components/constitution-page/song-list/song-list.component.html
- src/app/components/constitution-page/song-list/song-list.component.scss
- src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.html
- src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
- src/app/components/constitution-page/votes/votes-grade/votes-grade.component.scss
* Lors de l'ajout des chansons il n'y a plus d'icône neutre pouvant faire penser à des radios buttons.
* La barre de filtrage des utilisateurs et des chansons occupe désormais 100% de l'espace alloué pour mieux accommoder les petits écrans.
* Correction de l'utilisation de `text-overflowable` introduit en #52
* Correction du nombre de caractère pour le titre et auteur des chansons et du nom d'une constitution introduit en #52
> Correction pour 7ème Xénocratie

- src/app/components/constitution-page/song-list/song-list.component.html
- src/app/components/constitution-page/song-list/song-list.component.ts
- src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
- src/app/components/constitution-page/votes/votes-grade/votes-grade.component.ts
* Il est désormais possible d'ordonner les chansons en mettant en avant les favoris.
* Ajout des favoris dans la vue par tables.
* Déplacement des ordres sur les notes dans les filtres des utilisateurs. Ajout aussi le même support pour les tables.
> Ordonner par favoris

- src/app/components/constitution-page/constitution.component.html
- src/app/components/constitution-page/export/export.component.html
- src/app/components/constitution-page/export/export.component.scss
- src/app/components/constitution-page/export/export.component.ts
- src/app/components/constitution-page/owner/owner.component.html
* Onglet `EXPORT` est désormais disponible dans une constitution. Il est alors possible de télécharger les informations des chansons sous plusieurs formats (Google Sheet / CSV).
* Un format spécial de CSV est disponible pour les personnes ayant le rôle `Dev`.
> Onglet d'export des chansons d'une constitution

- src/app/components/template/scatter/scatter.component.ts
@thehyouz ne sait toujours pas que les nombres magiques c'est pas bien.
* Placement des lignes du scatter en fonction du nombre d'utilisateur (et pas seulement 7).
* Ajout d'une vérification qui évite que le graph crash si il y a une erreur dans les données fournies.
> Fix sur le nombre d'utilisateur affiché sur le graphe scatter des Rangs

- src/app/components/constitution-page/results/results-favorites/results-favorites.component.html
- src/app/components/constitution-page/results/results-favorites/results-favorites.component.ts
- src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.html
- src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.ts
- src/app/components/constitution-page/results/results-grade/grade-profile/grade-profile.component.html
- src/app/components/constitution-page/results/results-grade/grade-profile/grade-profile.component.scss
- src/app/components/constitution-page/results/results-grade/grade-profile/grade-profile.component.ts
- src/app/components/constitution-page/results/results-grade/results-grade.component.html
- src/app/types/results.ts
* Ajout d'une nouvelle table "Notes des participants" permettant de voir le détail des notes d'un participant en particulier.
* Ajout d'une nouvelle table "Favoris des participants" permettant de voir le détail des favoris d'un participant en particulier.
* Revision de la sous-section Profile de la page des résultats. En plus de la répartition des notes, de la moyenne et la variance maintenant sont ajouté les notes (rangé en ordre décroissant) et les favoris de l'utilisateur.
* Ajout du type `SongGrade`.
> Ajout de plus d'informations sur la page des résultats d'une grade constitution

- src/app/components/constitution-page/constitution.component.ts
- src/app/components/constitution-page/results/results-grade/results-grade.component.ts
- src/app/components/current-constitution-page/current-constitution-page.component.html
- src/app/components/join-constitution/join-constitution.component.ts
- src/app/types/routes.ts
* Rafraîchir la page d'une constitution va maintenant se rappeler de la sous-section.
* L'enum `ConstitutionSection` utilise désormais des strings au lieu de number.
* L'URL d'une page de constitution prend un paramètre supplémentaire et est désormais sous la forme suivante : `constitution/:cstID/:section`.
> Rappel d'une sous-section d'une constitution

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/components/constitution-page/constitution.component.ts
- src/app/components/constitution-page/owner/owner.component.html
- src/app/components/constitution-page/owner/owner.component.ts
* Le président d'une constitution peut désormais la faire supprimer.
* Passage à Chelys 2.6.0.
* Tous les utilisateurs sur la constitution supprimée sont redirigé vers la page des constitutions en cours avec un message en bas à droite.
* Le président doit d'abord désactiver un verrou avant de pouvoir supprimer la constitution.
Équivalent Kalimba : https://github.com/TableauBits/Kalimba/pull/32
> Ajout du support pour la suppression de constitution.

- src/app/components/invite-page/invite-page.component.ts
- src/app/services/auth.service.ts
- src/environments/environment.prod.ts
- src/environments/environment.ts
Cette PR accompagne [la PR équivalente sur Kalimba](https://github.com/TableauBits/Kalimba/pull/38) pour migrer le service vers Fly.io. Pour Yatga, cette migration implique simplement de changer l'URL du serveur dans l'environnement de production
- L'URL du serveur de Kalimba est maintenant celle de Fly.io
- Reformattage de certains fichiers
> Migration vers Fly.io

- src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
- src/app/components/constitution-page/votes/votes-grade/votes-grade.component.ts
* Dans la section `Zone Électorale`, il n'était pas possible de ré-initialiser l'ordre des chansons après avoir choisi un classement à partir du bouton `Réinitialiser`.
> Correction du bouton Réinitialiser pour le classement dans la Zone Électorale.

- src/app/components/home-page/home-page.component.html
- src/app/components/home-page/home-page.component.scss
- src/app/components/home-page/home-page.component.ts
- src/styles.scss
* Révision de la Home Page et ajout des releases Github sous la forme d'un `mat-accordion`.
* Le `.mat-expansion-indicator` devient blanc afin qu'on puisse le voir sur un fond gris.
> Ajout des releases Github sur la Home Page

- src/app/components/constitution-page/constitution.component.ts
- src/app/components/constitution-page/manage-songs/manage-songs.component.ts
* L'opérateur `||` ne peut pas être utilisé dans un switch-case pour regrouper plusieurs valeurs. Il ne fait que regarder la valeur de gauche.
* close #84
> Correction de l'utilisation de l'opérateur OR dans un switch-case

- src/app/components/constitution-page/constitution.component.html
- src/app/components/constitution-page/constitution.component.ts
- src/app/components/constitution-page/random-song/random-song.component.html
- src/app/components/constitution-page/random-song/random-song.component.ts
- src/app/components/constitution-page/song-list/song-list.component.html
- src/app/components/constitution-page/song-list/song-list.component.ts
- src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.html
- src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.ts
- src/app/components/constitution-page/votes/votes-grade/vote-navigator/vote-navigator.component.html
- src/app/components/constitution-page/votes/votes-grade/vote-navigator/vote-navigator.component.ts
- src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
- src/app/components/constitution-page/votes/votes-grade/votes-grade.component.ts
- src/app/components/constitution-page/votes/votes.component.ts
- src/app/types/extends/favorite.ts
Réduction de la duplication du code autour des favoris avec l'ajout d'une nouvelle classe.
* Création de la class `YatgaUserFavorites` qui permet de regrouper les implémentations des fonctions `canModifyFavorite`, `isAFavorite`, `noMoreFavorites` et `toggleFavorite` en un seul endroit. Pour les utiliser, il suffit d'extend cette classe et d'utiliser les attributs `constitution` et `favorites`.
* Les components `song-list` et `votes` ne reçoivent plus une map contenant tous les favoris mais seulement les favoris du auth user.
* Correction du nom de fonction `noMoreFavorties`.
> Refactor des fonctions des Favoris avec la classe YatgaUserFavorites

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/components/admin-page/new-constitution/new-constitution.component.scss
- src/app/components/admin-page/new-constitution/new-constitution.component.ts
- src/app/components/constitution-page/export/export.component.scss
- src/app/components/constitution-page/manage-songs/manage-songs.component.html
- src/app/components/constitution-page/manage-songs/manage-songs.component.scss
- src/app/components/constitution-page/manage-songs/manage-songs.component.ts
- src/app/components/constitution-page/optionnal-song-infos-button/optionnal-song-infos-button.component.html
- src/app/components/constitution-page/optionnal-song-infos-button/optionnal-song-infos-button.component.scss
- src/app/components/constitution-page/optionnal-song-infos-button/optionnal-song-infos-button.component.spec.ts
- src/app/components/constitution-page/optionnal-song-infos-button/optionnal-song-infos-button.component.ts
- src/app/components/constitution-page/results/results-favorites/results-favorites.component.scss
- src/app/components/constitution-page/results/results-grade/grade-average/grade-average.component.scss
- src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.scss
- src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.scss
- src/app/components/constitution-page/song-list/song-list.component.html
- src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.html
- src/app/components/constitution-page/votes/votes-grade/vote-navigator/vote-navigator.component.html
- src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
- src/app/types/utils.ts
- src/styles.scss
- tsconfig.json
Voir commentaire pour plus d'explications. Une constitution de test est disponible ici (code `ikC3jTvCNNnVV5bOb6bb`)
* Ajout de 5 nouvelles propriétés pour les chansons : 
* Date d'ajout / `addedDate`
* Année de sortie / `releaseYear`
* Album / `album`
* Genres musicaux / `genres`
* Titres alternatifs / `altTitles`
* Lorsque ajoutées, les nouvelles données sont disponible depuis un nouveau bouton soit directement sur la liste des chansons ou dans les navigateurs. Par exemple :
* La propriété `endDate` d'une constitution est mise à `undefined` plutôt que `null` afin que le champ soit ignoré par Kalimba.
* Passage à Chelys `2.12.0`
* Ajout du package `music-genres`
* Retrait des duplications de code pour le style d'un `mat-option`
* Close #106
* Dépend de : …
> Ajout des champs optionnels autour des chansons

- src/app/components/constitution-page/manage-songs/manage-songs.component.html
- src/app/components/constitution-page/manage-songs/manage-songs.component.scss
- src/app/components/constitution-page/manage-songs/manage-songs.component.ts
- src/app/components/navbar/navbar.component.html
- src/app/types/song-utils.ts
- src/app/types/utils.ts
* Ajout d'une boîte à cocher signalant qu'une chanson est instrumentale et qui remplace alors les langues données.
* Une typo dans le nom d'une variable empêchait de pouvoir sélectionner plusieurs langues à la fois.
* Le component manage-songs n'utilisait pas les variables SCSS de couleurs.
* Ajout de la valeur "Instrumental" et de sa clé "ins".
* Close #117
> Ajout de la valeur "Instrumental" comme langue

- src/app/app.module.ts
- src/app/components/constitution-page/optionnal-song-infos-button/optionnal-song-infos-button.component.ts
- src/app/components/constitution-page/results/results-constitution/results-constitution.component.html
- src/app/components/constitution-page/results/results-constitution/results-constitution.component.scss
- src/app/components/constitution-page/results/results-constitution/results-constitution.component.spec.ts
- src/app/components/constitution-page/results/results-constitution/results-constitution.component.ts
- src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.html
- src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.ts
- src/app/components/constitution-page/results/results-grade/grade-profile/grade-profile.component.html
- src/app/components/constitution-page/results/results-grade/grade-profile/grade-profile.component.ts
- src/app/components/constitution-page/results/results-grade/results-grade.component.html
- src/app/components/constitution-page/results/results-grade/results-grade.component.ts
- src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
- src/app/components/constitution-page/votes/votes-grade/votes-grade.component.ts
- src/app/components/template/histogram/histogram.component.ts
- src/app/types/song-utils.ts
* Ajout d'une sous-section "Constitution" dans les résultats. Pour le moment contient un graphe sur la répartition de l'année de sortie des chansons.
* Le component `app-histogram` peut maintenant être réutilisé en dehors de la répartition des votes de 1 à 10.
> Ajout de la sous-section "Constitution" dans la page des résultats

- src/app/app.module.ts
- src/app/components/constitution-page/constitution.component.ts
- src/app/components/constitution-page/navigator-song-display/navigator-song-display.component.html
- src/app/components/constitution-page/navigator-song-display/navigator-song-display.component.scss
- src/app/components/constitution-page/navigator-song-display/navigator-song-display.component.spec.ts
- src/app/components/constitution-page/navigator-song-display/navigator-song-display.component.ts
- src/app/components/constitution-page/random-song/random-song.component.html
- src/app/components/constitution-page/random-song/random-song.component.ts
- src/app/components/constitution-page/results/results-grade/grade-profile/grade-profile.component.ts
- src/app/components/constitution-page/song-list/song-list.component.ts
- src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.html
- src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.ts
- src/app/components/constitution-page/votes/votes-grade/vote-navigator/vote-navigator.component.html
- src/app/components/constitution-page/votes/votes-grade/vote-navigator/vote-navigator.component.ts
- src/app/components/constitution-page/votes/votes-grade/votes-grade.component.ts
- src/app/components/template/histogram/histogram.component.ts
- src/styles.scss
* Affichage de l'album d'une chanson dans les navigateurs si un album est spécifié.
* Ajout des informations optionnels dans l'onglet des chansons aléatoires.
* Correction de la mise à jours de certains éléments d'un histogramme.
* Application de la class `text-overflow` sur un titre d'une chanson trop long dans les navigateurs.
* Retrait de la class sass `custom-br` car inutilisé.
* Utilisation de la classe `NavigatorSongDisplayComponent` regroupant l'affichage du titre et d'un iframe d'une chanson.
> Refactoring des navigateurs avec la classe `NavigatorSongDisplayComponent`

- src/app/app.module.ts
- src/app/components/constitution-page/results/results-constitution/results-constitution.component.html
- src/app/components/constitution-page/results/results-constitution/results-constitution.component.ts
- src/app/components/template/calendar/calendar.component.html
- src/app/components/template/calendar/calendar.component.spec.ts
- src/app/components/template/calendar/calendar.component.ts
- src/app/components/template/heatmap/heatmap.component.ts
- src/app/types/charts.ts
- src/styles/echarts-theme.json
* Ajout d'un graph [Calendar](https://echarts.apache.org/examples/en/editor.html?c=calendar-simple) détaillant quand les chansons d'une constitution ont été ajoutés.
* Ajout d'un tooltip personnalisé pour la heatmap entre les utilisateurs.
* Ajout du support du dark theme pour les tooltips Echarts.
> Ajout d'un graph pour visualiser l'ajout des chansons d'une constitution dans le temps

- src/app/components/admin-page/new-constitution/new-constitution.component.ts
- src/app/components/constitution-page/navigator-song-display/navigator-song-display.component.html
- src/app/components/constitution-page/navigator-song-display/navigator-song-display.component.scss
- src/app/components/constitution-page/navigator-song-display/navigator-song-display.component.ts
- src/app/components/constitution-page/parameters/parameters.component.html
- src/app/components/constitution-page/parameters/parameters.component.scss
- src/app/components/constitution-page/parameters/parameters.component.ts
- src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.html
- src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.scss
- src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.ts
- src/app/components/constitution-page/song-list/song-list.component.html
- src/app/components/constitution-page/song-list/song-list.component.scss
- src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.ts
- src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
- src/app/components/constitution-page/votes/votes-grade/votes-grade.component.scss
- src/app/components/constitution-page/votes/votes-grade/votes-grade.component.ts
- src/app/services/song-property-manager.service.ts
- src/app/types/local-storage.ts
* Affichage des titres alternatifs, année de sortie et de l'album sur les cards et navigateurs.
* Correction du z-index des cards qui passaient alors au dessus de la navra.
* Création d'un nouveau service `SongPropertyManagerService`.
* En lien avec #118
> Ajout d'un service `SongPropertyManagerService`

- src/app/components/constitution-page/results/results-constitution/results-constitution.component.html
- src/app/components/constitution-page/results/results-constitution/results-constitution.component.ts
* Ajout de la fonction `propertyExists` qui renvoie le message "Aucune donnée disponible" pour les constitutions n'ayant pas de données optionnelles.
> Adaptation de l'affichage des résultats en fonction de la présence ou non de données optionnelles.

- src/app/components/constitution-page/results/results-constitution/results-constitution.component.html
- src/app/components/constitution-page/results/results-constitution/results-constitution.component.scss
- src/app/components/constitution-page/results/results-constitution/results-constitution.component.ts
* Ajout d'une table avec la répartition des genres des chansons d'une constitution dans la zone des résultats.
> Répartition des genres des chansons d'une constitution

- src/app/components/admin-page/new-constitution/new-constitution.component.html
- src/app/components/constitution-page/constitution.component.html
- src/app/components/constitution-page/manage-songs/manage-songs.component.html
- src/app/components/constitution-page/owner/grade-owner/grade-owner.component.ts
- src/app/components/constitution-page/owner/owner.component.html
- src/app/components/constitution-page/parameters/parameters.component.html
- src/app/components/constitution-page/random-song/random-song.component.html
- src/app/components/constitution-page/results/results-constitution/results-constitution.component.html
- src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.html
- src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.html
- src/app/components/constitution-page/results/results-grade/grade-relationship/grade-relationship.component.html
- src/app/components/constitution-page/song-list/song-list.component.html
- src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
- src/app/components/template/calendar/calendar.component.ts
Cette PR essaye de changer toutes les instances de texte "chanson" en "musique". Le premier commit à été fait avec les commandes suivantes (avec quelques changements exclus, notemment dans la liste des genres):
- `find . -type f -not -path "./node_modules/*" -not -path "./.git/*" -not -path "./.angular/*" -print0 | xargs -0 sed -i '' -e 's/chanson/musique/g'`
- `find . -type f -not -path "./node_modules/*" -not -path "./.git/*" -not -path "./.angular/*" -print0 | xargs -0 sed -i '' -e 's/Chanson/Musique/g'`
La plupart des instances ont été identifées, mais il est possible qu'il en manque par cause de fautes d'orthographe ou autres.
> Changement des mentions de "chanson" en "musique"

- package-lock.json
- package.json
- src/app/components/admin-page/new-constitution/new-constitution.component.html
- src/app/components/admin-page/new-constitution/new-constitution.component.ts
- src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.html
- src/app/components/constitution-page/results/results-grade/grade-grades/grade-grades.component.ts
- src/app/components/constitution-page/results/results-grade/grade-profile/grade-profile.component.html
- src/app/components/constitution-page/results/results-grade/grade-profile/grade-profile.component.ts
- src/app/components/constitution-page/results/results-grade/results-grade.component.html
- src/app/components/constitution-page/votes/votes-grade/vote-navigator/vote-navigator.component.html
- src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
- src/app/components/constitution-page/votes/votes-grade/votes-grade.component.ts
- src/app/components/template/histogram/histogram.component.ts
- src/app/types/song-utils.ts
* Les notes des constitutions ne sont maintenant plus limités entre 1 à 10, et la borne max peut être choisie avec l'attribut *maxGrade*.
* Ajout d'un check sur les valeurs et colonnes envoyées à un *Histogram* component pour éviter de générer le graphe inutilement et augmenter les performances.
* Passage à Chelys 2.15.2
* Dépend de https://github.com/TableauBits/Kalimba/pull/58
> Nouvelle borne max pour les notes d'une constitution

- src/app/app.module.ts
- src/app/components/constitution-page/results/results-constitution/results-constitution.component.html
- src/app/components/constitution-page/results/results-constitution/results-constitution.component.ts
- src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.html
- src/app/components/constitution-page/results/results-grade/grade-electoral/grade-electoral.component.ts
- src/app/components/template/inv-histogram/inv-histogram.component.html
- src/app/components/template/inv-histogram/inv-histogram.component.spec.ts
- src/app/components/template/inv-histogram/inv-histogram.component.ts
- src/app/types/charts.ts
* Les graphes des langues et des utilisateurs de la soirée électorale sont désormais des bar charts orientés sur l'axe des y plutôt que des pie charts pour plus de lisibilité quand beaucoup de valeurs sont affichées.
* La combinaison des languages est maintenant affichée à part dans le graphe illustrant les languages, plutôt qu'elles comptent de manière indépendante.
> Remplacement de certains pie charts par des bar charts

- src/app/components/constitution-page/constitution.component.html
- src/app/components/constitution-page/constitution.component.ts
- src/app/components/constitution-page/results/results-grade/results-grade.component.html
- src/app/components/constitution-page/results/results-grade/results-grade.component.ts
- src/app/components/constitution-page/song-list/song-list.component.html
- src/app/components/constitution-page/song-list/song-list.component.ts
- src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.html
- src/app/components/constitution-page/song-list/song-navigator/song-navigator.component.ts
- src/app/components/current-constitution-page/current-constitution-page.component.html
- src/app/components/current-constitution-page/current-constitution-page.component.ts
* Il est désormais possible de consulter les chansons et les résultats d'une constitution publique sans y être membre.
* Retrait de la colonne "Youtube Playlist" de la table présentant les constitutions en cours.
> Ajout d'un mode spectateur aux constitutions

- src/app/components/constitution-page/song-list/song-list.component.html
- src/app/components/constitution-page/votes/votes-grade/votes-grade.component.html
* Ajout d'un tooltip sur le titre des musiques affichées via les cartes afin de pouvoir lire le titre complet, même si celui-ci dépasse de la carte.
> Ajout d'un tooltip pour les titres des musiques
